Update daily_etl.yml

diff --git a/.github/workflows/daily_etl.yml b/.github/workflows/daily_etl.yml
--- a/.github/workflows/daily_etl.yml
+++ b/.github/workflows/daily_etl.yml
@@ -18,6 +18,34 @@ jobs:
       with:
         python-version: '3.8'
 
+    - name: Check secrets
+      run: |
+        for secret in TYPE PROJECT_ID PRIVATE_KEY_ID PRIVATE_KEY CLIENT_EMAIL CLIENT_ID AUTH_URI TOKEN_URI AUTH_PROVIDER_X509_CERT_URL CLIENT_X509_CERT_URL UNIVERSE_DOMAIN TABLE_ID ANALISTA_DADOS_KEY_API ANALISTA_BI_KEY_API CIENTISTA_DADOS_KEY_API ENGENHEIRO_DADOS_KEY_API; do
+          if [ -z "${!secret}" ]; then
+            echo "Error: Secret $secret is not set."
+            exit 1
+          else
+            echo "Secret $secret is set."
+          fi
+        done
+      env:
+        TYPE: ${{ secrets.TYPE }}
+        PROJECT_ID: ${{ secrets.PROJECT_ID }}
+        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
+        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
+        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
+        CLIENT_ID: ${{ secrets.CLIENT_ID }}
+        AUTH_URI: ${{ secrets.AUTH_URI }}
+        TOKEN_URI: ${{ secrets.TOKEN_URI }}
+        AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
+        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
+        UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
+        TABLE_ID: ${{ secrets.TABLE_ID }}
+        ANALISTA_DADOS_KEY_API: ${{ secrets.ANALISTA_DADOS_KEY_API }}
+        ANALISTA_BI_KEY_API: ${{ secrets.ANALISTA_BI_KEY_API }}
+        CIENTISTA_DADOS_KEY_API: ${{ secrets.CIENTISTA_DADOS_KEY_API }}
+        ENGENHEIRO_DADOS_KEY_API: ${{ secrets.ENGENHEIRO_DADOS_KEY_API }}
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
